version: "3"

services:
   node-server:
     tty: true
     build:
        context: .
        dockerfile: docker/nodejs/Dockerfile
     ports:
       - 1000:1000
     restart: unless-stopped
     volumes:
        - ./:/app